dist: xenial
language: cpp
compiler: clang
branches:
  only:
    - master
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - curl -f -T nickname-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -utnovits:$BINTRAY_API_KEY "https://api.bintray.com/content/tnovits/otus-cpp/nickname/$TRAVIS_BUILD_NUMBER/nickname-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"

